@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/chat/message/conversation-list
Content-Type: application/json
Accept: application/json
withCredentials: true

###
# GET {{baseUrl}}/{{urlPath}}/chat/message/user/<receiverId>
GET {{baseUrl}}/{{urlPath}}/chat/message/user/66b38c4bcb36be995b7f14e8
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "",
  "receiverId": "66b38c4bcb36be995b7f14e8",
  "receiverUsername": "Pranav21",
  "receiverAvatarColor": "red",
  "receiverProfilePicture": "https://res.cloudinary.com/duojkrgue/image/upload/v1723042893/r-connect/66b38c4bcb36be995b7f14e8",
  "body": "Hello Pranav",
  "gifUrl": "",
  "isRead": false,
  "selectedImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/add-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "66b38b8dcb36be995b7f14de",
  "userTwo": "66b38c4bcb36be995b7f14e8"
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/remove-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "",
  "userTwo": ""
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/mark-as-read
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "senderId": "66b38b8dcb36be995b7f14de",
  "receiverId": "66b38c4bcb36be995b7f14e8"
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

# For this endpoint, the type is either add or remove
{
  "conversationId": "66b38d1fcb36be995b7f14f4",
  "messageId": "66b38d1fcb36be995b7f14f3",
  "reaction": {"like": 0,"love": 0,"happy": 1,"sad": 0,"wow": 0,"angry": 0},
  "type": "happy"
}

###
# DELETE {{baseUrl}}/{{urlPath}}/chat/message/mark-as-deleted/<messageId>/<senderId>/<receiverId>/<type>
DELETE {{baseUrl}}/{{urlPath}}/chat/message/mark-as-deleted/66b38d1fcb36be995b7f14f3/66b38b8dcb36be995b7f14de/66b38c4bcb36be995b7f14e8/deleteForMe
# For this endpoint, the type is either deleteForMe or deleteForEveryone
Content-Type: application/json
Accept: application/json
withCredentials: true
